import type { Metadata } from 'next'
import { ThemeProvider } from '@/providers/theme-provider'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import prisma from '@/lib/db'
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getData(userId: string) {
  try {
    if (userId) {
      const data = await prisma.user.findUnique({
        where: {
          id: userId,
        },
        select: {
          colorScheme: true,
        },
      })
      if (data) {
        return data
      }
    }
  } catch (error) {
    console.log(error)
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { getUser } = getKindeServerSession()
  const user = await getUser()
  const data = await getData(user?.id as string)

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${data?.colorScheme ?? 'theme-zinc'}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
